#!/bin/sh

SCRIPT="cd /opt/greetings_src && npm start"
PID=$(ps -ef | grep node | grep -v grep | awk '{print $2}')
USER=root

LOGFILE=/var/log/greetings.log

start() {
  if [ -z "$PID" ]; then
    echo 'Starting Greetings API' >&2
    local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
    su -c "$CMD" $USER
    echo 'Greetings API started' >&2
  else
    echo "Greetings API already running"
  fi
}

stop() {
  if [ -z "$PID" ]; then
    echo "Greetings API not running"
  else
    echo "Stopping Greetings API"
    kill -9 ${PID}
  fi
}

status() {
  if [ -z "$PID" ]; then
    echo "Greetings API not running"
  else
    echo "Greetings API running with PID $PID"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac